services:
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
            - 'certbot-etc:${LETSENCRYPT_CONF_PREFIX}'
        restart: unless-stopped
        ports:
            - "8000:8000"
            - "9001:9443"
        environment:
            TZ: '${LOCAL_TIMEZONE}'
        command: '--sslcert /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem --sslkey /etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem'

volumes:
    portainer_data:
        name: portainer_data
    certbot-etc:
        external: true
